# Generated by Django 4.0 on 2022-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='jobs'),
            preserve_default=False,
        ),
    ]
